apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ansh-Pandey-NucleusTeq/argo_cd.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPlicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true